### ISSUE TITLE
Endpoints for various status codes

### ISSUE THREAD

**Issue by voltagex** [Mashape/mockbin#11]
See also http://httpbin.org/

Maybe you don't want to replicate functionality but I can see the utility in http://mockbin.com/404 and http://mockbin.com/418

**Comment by ahmadnassri** [comment]
@voltagex already exists! in fact all the httpbin endpoints exist here too :)

see http://mockbin.com/docs#utility-endpoints for full documentation.

**Comment by ahmadnassri** [comment]
`/status/200`
`/status/404`

can even send custom "reason" message:

`/status/500/yolo`

**Comment by voltagex** [comment]
Sorry, missed this one.
