### ISSUE TITLE
HAR format should be optional

### ISSUE THREAD

**Issue by bitwit** [Mashape/mockbin#18]
We'd like to use this with an existing service to mock new features in the API under development, but we don't use HAR format.
It would be ideal if the WHOLE body and content type could be specified rather than just the 'content' portion.

**Comment by ahmadnassri** [comment]
so with minimal requirements it would look like this:

```json
{
  "content": {
    "mimeType": "text/plain", 
    "text": "Hello"
  }
}
```

- `status`, and `statusText`, will default to `200` & `OK`.
- `Content-Type` header will default to `mimeType`

**Comment by bitwit** [comment]
Well our API responses typically look like:

```javascript
{
    success: true,
    payload: ['array of stuff']
}
```

So we're hoping to have a way to directly return a body like that, with payload in the root and containing JSON. The additional HAR headers aren't the problem so much as that my body ends up nested inside 'content' as text even if I say the content type is `application/json`

So I was hoping there was maybe a way to either select `HAR` and get this format or maybe a `raw` where i can indicate the content type and dump a stringified JSON body

If there's some way we can help with the feature, we're not afraid to roll our sleeves up

**Comment by ahmadnassri** [comment]
oh ... methinks we are talking about two different things and perhaps you are using this wrong ... 

after creating a bin, accessing it will give you the response body directly:

```shell
curl mockbin.org/bin/create -H "Content-Type: application/json" --data '{"status": 200,"statusText": "OK","httpVersion": "HTTP/1.1","headers": [{"name": "content-type","value": "application/json"}],"cookies": [],"content": {"mimeType": "application/json","text": "{\"success\": true, \"payload\": [\"array of stuff\"]}","size": 0},"redirectURL": "","bodySize": 0,"headersSize": 0}'
```

```shell
curl -v http://mockbin.com/bin/8fbdd762-3c3e-4429-8ab1-2338b594b705
```

###### result

```
> GET /bin/8fbdd762-3c3e-4429-8ab1-2338b594b705 HTTP/1.1
> User-Agent: curl/7.35.0
> Host: mockbin.com
> Accept: */*
> 
< HTTP/1.1 200 OK
< Date: Mon, 13 Apr 2015 21:00:30 GMT
< Content-Type: application/json; charset=utf-8
< Content-Length: 48
< Connection: keep-alive
< Set-Cookie: __cfduid=df778ad7ddd1adf14c39590ccb5ade4041428958830; expires=Tue, 12-Apr-16 21:00:30 GMT; path=/; domain=.mockbin.com; HttpOnly
< Etag: W/"30-e5878040"
< Vary: Accept-Encoding
< Via: 1.1 vegur
* Server cloudflare-nginx is not blacklisted
< Server: cloudflare-nginx
< CF-RAY: 1d6a19d186810d8b-SJC
< 
{"success": true, "payload": ["array of stuff"]}
```

**Comment by bitwit** [comment]
I was definitely using it wrong! Okay I see it working as expected now. I was confused by the `/bin/xxx/view` page and thought it was my final output.

Thanks!

**Comment by ahmadnassri** [comment]
perhaps better documentation is needed then :)
