### ISSUE TITLE
All the HTTP methods are working  even-though ,if method specified 

### ISSUE THREAD

**Issue by Vidhyadharantechdays** [Mashape/mockbin#44]
I have created a mockbin for HTTP method "PATCH" 

with this request 
http://mockbin.org/bin/bfdc4273-ff50-4141-bef6-28810a6291dd/view
```
{
  "status": 200,
  "statusText": "OK",
  "httpVersion": "HTTP/1.1",
  "headers": [],
  "method": "PATCH",
  "cookies": [],
  "content": {
    "mimeType": "text/plain",
    "text": "{\n\"response\":\"Patched successfully\"\n}",
    "size": 0
  },
  "redirectURL": "",
  "bodySize": 0,
  "headersSize": 0
}
```
When i tried in Rest client it is not restricting only for PATCH method

**Comment by ahmadnassri** [comment]
mockin accepts all methods and does not filter / restrict any methods.

defining a "method" properly in response, does not forbid any other methods.
