### ISSUE TITLE
Log entries no longer showing

### ISSUE THREAD

**Issue by kaustria** [Mashape/mockbin#47]
This used to work a couple of months ago, but it seems that the log entries are no longer returned  / history is no longer viewable. 

Repro:
1. Creating a new bin
2. Send POST or GET requests 
3. GET {binID}/log returns empty entries []

**Comment by ahmadnassri** [comment]
@kaustria thanks for reporting, it's now fixed.

**Comment by kaustria** [comment]
Thank you @ahmadnassri !
