### ISSUE TITLE
Mock Bin is not working correctly on Mockbin.org via create bin

### ISSUE THREAD

**Issue by Kaiyuan90** [Mashape/mockbin#49]
Example: http://mockbin.org/bin/afd9715a-63bb-4cad-98d5-8505d2ddaef0/detail

![image](https://cloud.githubusercontent.com/assets/5882263/16438912/468e3f18-3d68-11e6-8964-c1ee7acd276c.png)

**Comment by ahmadnassri** [comment]
investigating ...

**Comment by ahmadnassri** [comment]
should be fixed now.

**Comment by luanmuniz** [comment]
This problem is back

**Comment by DeonKuhn** [comment]
Having the same problem 
https://mockbin.org/bin/212e66e5-ff57-47a3-8e65-fb825534b42a/view
