### ISSUE TITLE
Mockbin.org examples not loading

### ISSUE THREAD

**Issue by keyscores** [Mashape/mockbin#51]
As of June 29 2016, seems like the mockbin.org sample bin is down. Thought you would like to know...
Going to mockbin.org, and clicking the button 'View Sample Bin' shows a bin with no settings. 
I noticed and I use this bin occasionally to test.

**Comment by ahmadnassri** [comment]
thanks, fixed now.

**Comment by keyscores** [comment]
Thanks. I think you meant the example to say { foo: "Hello World"}. Instead it's missing an L: "Hello Word". Thanks again!

**Comment by keyscores** [comment]
@ahmadnassri  Seems like this is breaking in production again.

**Comment by lpgeiger** [comment]
@ahmadnassri any updates? Still seems down...

**Comment by ahmadnassri** [comment]
The Mashape team is not maintaining this anymore ... a fork might be in order...
