### ISSUE TITLE
Cannot access bottom left navigation items in documentation

### ISSUE THREAD

**Issue by fharper** [Mashape/mockbin#6]
As you can see in this video [1], you cannot access the bottom items on the documentation elements on the left depending of your resolution, since it's fixed, even if you scroll the documentation itself.

[1] https://dl.dropboxusercontent.com/u/13087140/Mockbin-scroll.mp4

**Comment by ahmadnassri** [comment]
this is a bug for [mashape/mockbin.com](https://github.com/mashape/mockbin.com)

**Comment by fharper** [comment]
I created under the right repository.

**Comment by ahmadnassri** [comment]
thanks :+1: :)
